import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="w-full antialiased">
        <div className="main flex w-full flex-col justify-between">
          <main className="relative flex w-full flex-[1_0_0] justify-center px-6">
            {children}
          </main>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
