import "./globals.css";

import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Header } from "@/components/Header";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={clsx(inter.className, "w-full")}>
      <body className="w-full antialiased relative">
        <div className="flex w-full flex-col justify-between">
          <ThemeProvider attribute="class" defaultTheme="system">
            <Header />
            {children}
          </ThemeProvider>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
